### ISSUE TITLE
.onNext() versus .next()

### ISSUE THREAD

**Issue by sylvesterjakubowski** [staltz/rxjs-training#4]
In Example 4:

`    observer.onNext(123);`

Gives:

`TypeError: observer.onNext is not a function
    at Timeout._onTimeout (path/to/file)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)`

This is due to http://stackoverflow.com/a/36613646/390829

Changing to 

`observer.next(123);`

Fixes the issue.

**Comment by staltz** [comment]
This training material was crafted for RxJS v4, not v5.
